import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent.enquiry import Enquiry


def readback(e: Enquiry) -> str:
    """Deterministic confirmation string. Never generated by LLM."""
    return (
        f"Confirming. {e.applicant_name}, {e.exam} score {e.score}, "
        f"interested in {e.course}. Campus visit on {e.visit_slot}. "
        f"Should I book this?"
    )


if __name__ == "__main__":
    test_enquiry = Enquiry(
        caller_name="Ramesh",
        applicant_name="Aryan",
        course="B.Tech Computer Science and Engineering (AI & ML)",
        exam="JEE Main",
        score=91,
        visit_slot="Saturday 11 AM"
    )
    print(readback(test_enquiry))